export const EAction = {
    FETCH_DATA_APP_START          : 'FETCH_DATA_APP_START',
    FETCH_DATA_APP_FAIL           : 'FETCH_DATA_APP_FAIL',
    FETCH_DATA_APP_COMPLETE       : 'FETCH_DATA_APP_COMPLETE',
    FETCH_DATA_CONTAINER_START    : 'FETCH_DATA_CONTAINER_START',
    FETCH_DATA_CONTAINER_FAIL     : 'FETCH_DATA_CONTAINER_FAIL',
    FETCH_DATA_CONTAINER_COMPLETE : 'FETCH_DATA_CONTAINER_COMPLETE',
};